# ./.tmuxinator.yml

name: cli-talk
root: .

tmux_command: byobu

windows:
    - ranger:
        - ranger
    - bat:
        - bat slides.md
    - (porn) colorls:
        - lc
    - (porn) lolcat:
        - la | lolcat
    - (porn) no-more-secrets:
        - la | nms | lolcat

